apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../cluster-wide-notls

# Adds namespace to all resources.
namespace: authorino

patchesStrategicMerge:
- patches/oidc_server_cert_patch.yaml
