apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
  labels:
    app: authorino
    svc: echo-api
spec:
  selector:
    matchLabels:
      app: authorino
      svc: echo-api
  template:
    metadata:
      labels:
        app: authorino
        svc: echo-api
    spec:
      containers:
      - name: authorino
        image: quay.io/3scale/authorino:echo-api
        env:
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: echo-api
  labels:
    app: authorino
spec:
  selector:
    app: authorino
    svc: echo-api
  ports:
    - port: 3000
      protocol: TCP
